name: Release-Please (Build; Publish)
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          package-name: release-please-action
          release-type: node
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: '@octopusdeploy'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.INTEGRATIONS_NPM_ACCESS_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}